import type { Metadata } from "next";
import localFont from "next/font/local";
import { Plus_Jakarta_Sans, Space_Grotesk } from "next/font/google";

import "./globals.css";

const jakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-body",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-display",
});

const brogetta = localFont({
  src: "../src/assets/fonts/BROGETTA-Regular.otf",
  variable: "--font-brogetta",
});

const quera = localFont({
  src: "../src/assets/fonts/Quera DEMO.otf",
  variable: "--font-quera",
});

export const metadata: Metadata = {
  title: "OpenChats",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
			className={`
				${jakartaSans.variable}
				${quera.variable}
      	${spaceGrotesk.variable}
       	${brogetta.variable}
        h-full antialiased bg-primary`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
